### ISSUE TITLE
waiting queue

### ISSUE THREAD

**Issue by gs-spadmanabhan** [rafaelfirmino/amqp-support#2]
Hi,

Could you give me an example where the waiting queue will be used and how the message from waiting queue will be pushed back to the main queue?

**Comment by rafaelfirmino** [comment]
Hello.

1291/5000
We will always create a queue waiting for a delayed delivery. At JMS we have this concept too. For example, I want to create a JOB (Like Quartz or Spring Batch) that every 30 minutes does something, so I send a message to the queue that will be consumed in 30 minutes, when the consumer receives it again, it does its job, and sends another message to 30 minutes later.
Another example of an application is to not have concurrency conflicts in the same database, my process X is using the database for the entity id 1 and in 5 minutes the process Y will receive a message and manipulate the entity id 1 as too.

In Rabbit, we have arguments at the time of queue construction. We have an argument called x-message-ttl, in it you define the time your message will have to be consumed, if it is not consumed in that time it dies.
When a message dies, it goes to DLQ, as in the JMS concept. At the time of the queue construction we also have an argument that defines the name of its DLQ, there we put the name of the main queue. So, a message arrives in a queue who has no consumer listening, the message will waiting, after X minutes defined in the TTL it will expire and will be sent to the DLQ, which will be the name of our main queue, which has a consumer listening.

Sorry my english.
